# Generated by Django 4.0.6 on 2022-09-25 07:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_data'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='data',
            options={'verbose_name_plural': 'Data'},
        ),
        migrations.RemoveField(
            model_name='data',
            name='user',
        ),
    ]
